### ISSUE TITLE
When using withStyles, i get an error after reloading the page

### ISSUE THREAD

**Issue by Flaxxas** [Flaxxas/homepage#1]
I get this error, when i try to add styles to a component using material ui withStyles. Everything looks fine when i run `npm run dev`, but after reloading the page all styles are missing and this error is thrown: 

> Warning: Prop `className` did not match. Server: "App-root-51" Client: "App-root-1"

**Comment by Flaxxas** [comment]
Can you help me, @HaNdTriX?

**Comment by HaNdTriX** [comment]
https://github.com/mui-org/material-ui/blob/v1-beta/examples/nextjs
